### ISSUE TITLE
setItemDetailsRenderer in Vaadin 14.4.5 produce (TypeError) : $0.$connector

### ISSUE THREAD

**Issue by davidclaesson** [vaadin/vaadin-grid#2116]
### Description
Several (TypeError) : $0.$connector produced when using nestled grids. Didn't get these errors in 14.4.4 

e.g (TypeError) : 
(TypeError) $0.$connector.reset is not a function
(TypeError) : $0.$connector.set is not a function

### Expected outcome
No TypeErrors should be shown

### Actual outcome
Several (TypeError) is shown

### Live Demo
none

### Steps to reproduce
	    grid.setItemDetailsRenderer(new ComponentRenderer<>(item -> {
			return new Grid<>();
			})
		);

### Browsers Affected
Only tested chrome

- [X ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by yuriy-fix** [comment]
The issue was caused by https://github.com/vaadin/vaadin-flow-components/commit/cbc6c7cbe4b97c2160822ee63c557649d04fc2e9. Problematic commit was reverted later on with https://github.com/vaadin/vaadin-flow-components/commit/2b2aa05c57c883fb3a7154a23db2036bcde8869c.
