### ISSUE TITLE
Vaadin-grid doesn't work with Vaadin 10.0.0.alpha9 and fails with `grid._createPropertyObserver is not a function`

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid#1152]
### Description
Vaadin-grid doesn't work with Vaadin 10.0.0.alpha9 and fails with `grid._createPropertyObserver is not a function`. By including the `com.vaadin:vaadin:10.0.0.alpha9` dep into the project the `com.vaadin:vaadin-grid-flow:1.0.0.alpha3` is added on the classpath; by adding bower dependency of `"vaadin-core": "v10.0.0-alpha9"` the `"_target": "4.1.0-alpha1"` grid element is added to `bower_components` (yup I'm not using webjars nor vaadin bom).

### Expected outcome
Grid should just work. It works with vaadin:10.0.0.alpha8.

### Actual outcome
Grid fails with `grid._createPropertyObserver is not a function` in the JavaScript console.

### Steps to reproduce

1. Clone https://github.com/mvysny/karibu-dsl
2. Edit `build.gradle` and use `ext.vaadin10_version = '10.0.0.alpha9'`
3. Replace `@InternalContainerAnnotationForConvert` with `@Convert.Container` in `ReviewsList.kt`
4. `./gradlew build`
5. `./gradlew example-v10:appRun`
6. Browse locahost:8080 and go to the reviews tab.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by mvysny** [comment]
![screenshot from 2017-12-12 10-29-07](https://user-images.githubusercontent.com/254091/33874397-50417202-df27-11e7-9de1-077453b01f38.png)

**Comment by mvysny** [comment]
Tried to upgrade vaadin-grid element to 4.1.0-alpha2, the issue persists.

**Comment by tomivirkki** [comment]
Please report in the correct repository (Flow). Vaadin-grid [works fine](https://cdn.vaadin.com/vaadin-grid/4.1.0-beta1/demo/#grid-basic-demos) by itself so there's something wrong in the integration.

**Comment by jouni** [comment]
Heh, the correct repository is actually `vaadin-grid-flow`, not the Flow repo directly.
